packages:
  - '.'
  - 'docs/note'

catalogs:
  build:
    '@element-plus/icons-vue': ^2.3.1
    '@sugarat/theme': ^0.5.9
    element-plus: ^2.7.2
    pagefind: ^1.3.0
    sass: ^1.76.0
    vitepress: 2.0.0-alpha.15
    vue: 3.5.12
  dev: {}
  type:
    typescript: ^5.4.5

